---
- hosts: toolsserver
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.repo-epel
    - geerlingguy.ansible